Repository 2factorauth/passkeys, pull requests merged in 2024-04, with the labels that each got.

#8 Update MangaDex
  icons/m/mangadex.org.svg
Labels: update site

#7 Add sites from the Bitwarden Passkeys Index
  entries/b/braunhousehold.com.json
  entries/c/carnival.com.json
  entries/d/dinero.dk.json
  entries/v/vercel.com.json
  icons/b/braunhousehold.com.svg
  icons/c/carnival.com.png
  icons/v/vercel.com.svg
Labels: add site, multiple sites

#10 Add NHS
  entries/n/nhs.uk.json
  icons/n/nhs.uk.svg
Labels: add site
